In [5]:
import numpy as np

In [3]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
arreglo = np.arange(100)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
arreglo = arreglo.reshape(10,10)
arreglo

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
arreglo[2:5,::2]

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [26]:
arreglo2d = np.arange(30).reshape(6,5)
arreglo2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [28]:
mask = arreglo2d < 20
mask


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [29]:
arreglo2d[mask]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
arreglo2d = np.arange(9).reshape(3,3)
arreglo2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arreglo2d.sum()

36

**eje 0 columnas**

In [39]:
arreglo2d.sum(axis = 0)

array([ 9, 12, 15])

**eje 1 filas**

In [40]:
arreglo2d.sum(axis = 1)

array([ 3, 12, 21])

In [41]:
arreglo2d = np.arange(9)

In [42]:
arreglo2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
arreglo2d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Ejercicio1
1. Que operaciones se pueden hacer tanto en un arreglo de numpy como en una lista
2. Que operaciones se pueden hacer en un arreglo numpy pero no en una lista
2. Cual es la diferencia entre un arreglo de forma shape(n) shape(n, 1) shape (1, n)

In [50]:
lista = [1, 2, 3 , 4]
arreglo = np.array(lista)
lista
arreglo


array([1, 2, 3, 4])

In [53]:
for item in lista:
    print (item)

1
2
3
4


In [55]:
for item in arreglo:
    print (item)


1
2
3
4


In [57]:
print(len(lista))
print(len(arreglo))


4
4


**No se pueden utilizar**

In [58]:
lista.pop()


4

In [59]:
lista.pop()

3

In [60]:
lista

[1, 2]

In [63]:
lista.append(3)
lista.append(4)

In [64]:
arreglo.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [81]:
arreglo.reshape(1,4)

array([[1, 2, 3, 4]])

In [70]:
arreglo.shape


(4,)

In [75]:
arreglo.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [76]:
arreglo.reshape(2,2).shape

(2, 2)

In [78]:
arreglo.reshape(2,2,1)

array([[[1],
        [2]],

       [[3],
        [4]]])

In [79]:
arreglo.reshape(2,2,1).shape


(2, 2, 1)

**Ejercicio 2**
1.  Escribir un arreglo con números enteros del 0 al 9 pista arange
2.  Escribir un arreglo con 100 números equiespaciados del 0 al 9 Lnspace

In [84]:
arreglo = np.arange(0,10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arreglo2 = np.linspace(0,9,100)

arreglo2

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

**Ejercicio 3**
Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son menores que 50

In [103]:
arreglom = np.arange(0,101)
arreglom

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [99]:
mask = arreglom < 50
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [100]:
arreglom[mask]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [104]:
np.arange(0,101)[np.arange(0,101) < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

**Ejercicio 4**
Crear un arreglo de ceros shape (5,10)
Remplazar la segunda y cuarta fila con unos
Remplazar la tercera y octava columna con dos (2)

In [6]:
arreglo = np.zeros(50)
arreglo

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
arreglo.reshape(5,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [135]:
arreglo

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arreglo[1:18:2] = 1

arreglo

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Revisar este tema de remplazo en la matriz**