# Funciones

Una función es un bloque de código que sólo corre cuando es llamado.

In [ ]:
def par_o_impar(numero):
    if numero %2 == 0:
        print('Es par')
    else:
        print('Es impar')

Notar que si ejecutamos la celda no ocurre nada apreciable. Si llamamos a la función

In [ ]:
par_o_impar

Python nos dice, de una forma no muy clara, que se trata de una función. Las funciones se llaman con paréntesis:

In [ ]:
par_o_impar()

Y en este caso, arroja un error porque falta un argumento, `numero`. Las dos siguientes son equivalentes:

In [ ]:
par_o_impar(numero = 9)
par_o_impar(9)

Al tener un solo argumento, en este caso no hay mucho lugar a confusión, pero las funciones pueden tener muchos argumentos:

In [ ]:
def division(dividendo, divisor):
    print(dividendo/divisor)

Entonces podemos llamar a la función pasándole los argumentos en orden, o explicitando el valor de cada argumento:

In [ ]:
division(4,2)
division(divisor = 4, dividendo = 2)  #notar que asi no nos tenemos que preocupar por el orden

También, pueden tener argumentos *por default*, que si no explicitamos, toman un valor predefinido:

In [ ]:
def division(dividendo, divisor = 2):
    print(dividendo/divisor)

In [ ]:
division(9)
division(9, 3) 
division(dividendo = 9, divisor = 3) 
division(9, divisor = 3) 

### `return`

Las funciones pueden devolver resultados

In [ ]:
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar

In [ ]:
resultado_division = division(9,3)

In [ ]:
print(resultado_division)

Y, si lo necesitamos, podemos hacer que devuelvan más de un resultado

In [ ]:
def division_y_producto(numero_1,numero_2):
    div = numero_1/numero_2
    prod = numero_1*numero_2
    return div, prod

### Son equivalentes
# def division_y_producto(numero_1,numero_2):
#     return numero_1/numero_2, numero_1*numero_2

In [ ]:
resultados = division_y_producto(10,5)
print(resultados)

Notar la diferencia

In [ ]:
resultado_1, resultado_2 = division_y_producto(10,5)
print(resultado_1, resultado_2)

### Namespaces and Scope

Encontrar la diferencia entre las siguientes celdas:

In [ ]:
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

In [ ]:
divisor = 5
def division(dividendo):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

In [ ]:
divisor = 5
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

**Investigar:** ¿qué es una variable global?¿Y una variable loca?¿Qué es un Namespace?

### Funciones Lambda (Anónimas)

Una función `lambda` es una forma conveniente de crear una función en una sola línea. También se las conoce como funciones anónimas, ya que no tienen nombre, sino que se asignan a una variable.

In [ ]:
lambda_division = lambda x,y: x/y
lambda_division(80,10)

Algunas características:
1. Pueden tener cualquier cantidad de argumentos, pero solo una expresión
1. No necesitan un return
1. Muy cómodas para crear funciones rápido
1. Se combinan muy bien con funciones como `map()`, `filter()`, `apply()`, `applymap()`, etc.

Existen algunas diferencias sutiles entre una función creada con `def` y una función lambda, pero para nuestros objetivos basta con saber que una función lambda es una forma rápida de crear funciones sencillas.

### Extra: documentando funciones

Cuando creemos funciones es conveniente decumentarlas, así si volvemos meses después a nuestro código, o se lo compartimos a alguien, podemos entender qué hace sin tener que leer y entenderlo completamente. Es decir, de la misma forma que hacemos con muchas de las funciones de las librerías que venimos usando. Hay muchos formatos para documentar una función, pero en general incluyen: qué hace la función, cuales son sus argumentos, y cuáles son sus returns. A veces, también algún ejemplo mostrando cómo se usa. El grado de detalle depende del tiempo y de la complejidad de la función. Recomendamos siempre documentar las funciones, aunque sea de forma breve.

Dejamos un formato de documentación a modo de ejemplo. En general, se estila documentar en inglés, pero vamos a hacer una excepción.

In [ ]:
def division_y_producto(numero_1,numero_2):
    '''
    Dados dos numeros, devuelve su division
    y su producto.
    
    Arguments:
    numero_1 -- dividendo, primer multiplicando
    numero_2 -- divisor, segundo multiplicando
    
    Returns:
    div -- la division entre los dos numeros
    prod -- el producto entre los dos numeros
    '''
    
    div = numero_1/numero_2
    prod = numero_1*numero_2
    return div, prod

division_y_producto(1,3)

Notar que si ahora ponemos `help()` de nuestra función, devuelve la documentación que creamos.

In [ ]:
help(division_y_producto)

También, si usamos shift+tab como hacemos con las otras funciones de las librerías.

**Ejercicio**

1. Crear una función que tome como entrada dos arreglos de Numpy. Luego, que chequee si tienen el mismo tamaño; si no es así, que imprima un mensaje indicando que no tienen el mismo tamaño. Si tienen el mismo tamaño, que haga las siguientes operaciones:
    1. Crear un nuevo arreglo con el resultado de las resta de los dos arreglos originales.
    1. Elevar al cuadrado ese arreglo.
    1. Sumar todos los elementos y dividir por la cantidad de elementos.
    1. Devuelva la raiz de ese resultado.


In [12]:
import numpy as np


def RMSE(arreglo_1, arreglo_2):
    '''
    Este método sirve para...    
    Arguments:
    arreglo_1 -- Este es el primer parámetro o argumento
    arreglo_2 -- Este es el segundo parámetro o argumento
    '''
    resta = arreglo_1 - arreglo_2
    cuadrado = resta * resta
    suma = cuadrado.sum() / cuadrado.shape[0]
    raiz = pow(suma, 2)
    return resta, cuadrado, suma, raiz

np.random.seed(10)
arreglo1 = np.arange(5)
arreglo2 = np.random.randint(1, 100, 5)

print (arreglo1)
print (arreglo2)

raiz, resta, cuadrado, suma = RMSE(arreglo1, arreglo2)
print (resta)
print (cuadrado)
print (suma)
print (raiz)


   

[0 1 2 3 4]
[10 16 65 29 90]
[ 100  225 3969  676 7396]
2473.2
6116718.239999999
[-10 -15 -63 -26 -86]


Testeamos el resultados

In [ ]:
np.random.seed(10)  # que hace esta linea?
arreglo_1 = np.random.randint(-10,10, 50)
arreglo_2 = np.random.randint(-10,10, 50)
print(arreglo_1)
print(arreglo_2)

In [ ]:
RMSE(arreglo_1, arreglo_2)

Debería dar como resultado 7.48732

In [ ]:
np.random.seed(10)  # que hace esta linea?
arreglo_1 = np.random.randint(-10,10, 25)
arreglo_2 = np.random.randint(-10,10, 50)
print(arreglo_1)
print(arreglo_2)

In [ ]:
RMSE(arreglo_1, arreglo_2)

Debería dar como resultado un mensaje indicando que no tienen el mismo tamaño.

2. Documentar brevemente la función creada.